### ISSUE TITLE
Pausing a game should not affect future games

### ISSUE THREAD

**Issue by ddrinka** [syniosis76/canoepoloscoreboard#2]
### Expected Behavior
Pausing a game deducts from that game's total game time.  If a game slot is 30 minutes with two 10-minute halves and a 2-minute rest, pausing for 3 minutes should not affect the start of the next game.

### Current Behavior
Pausing a game for any amount of time moves all future games forward by that amount of time.

### Proposed fix
Pausing a game deducts from game-time without affecting future games, until the total amount of pauses exceeds the total game length, at which point future games begin to delay.

**Comment by ddrinka** [comment]
@syniosis76 Here in the US we schedule fairly long game slots (30-35 minutes is typical), but expect games to start precisely when they're scheduled, rather than advancing or delaying games later in the afternoon.  We've talked about disabling the pause functionality completely for non-final games, or training time keepers on how to reset the start time of the next game in the case of a pause, but we think the best solution would be that proposed above.

It might make sense to add one additional configuration for every game--the minimum required time to allow one team to exit the pitch and another to enter.  If the total amount of pause time exceeds the game time minus the "team swap" time, that's when future games begin sliding.  That leaves a guaranteed cushion before the next game begins.

Would you accept a pull request for this functionality?  Can you speak to how you think it should work from NZ's tournament styles?

**Comment by syniosis76** [comment]
I have always wanted it to work as you suggest but have not implemented it until now.

@ddrinka I would accept a pull request for this or any other improvement, but I have been thinking about it and already have a pretty good idea of what to do so I'll work on it this evening.

I don't think that it is necessary to have a setting per game. I thing that a global config defaulted to 2 minutes should be plenty. We can consider a per-game setting later on if it is required.

On a similar note I have been thinking that a game level setting for "Requires Result" for games that need to go to golden goal. Are there any other game level settings you would find useful?

**Comment by syniosis76** [comment]
@ddrinka I have committed a change to master that implements a MiimumTimeBetweenGames setting.
This is defaulted to 2 minutes and is settable in app settings (in Scoreboard.exe.config) but is not settable in the UI at this point.

This comes into play when you pause, add an extra period, or choose to start the next game in a set amount of time.

It does not effect manually changing game time which always change the following games and times. When you are editing the times for a game you should also pay attention to the start time of the following game.

I have not done a build at this point as it needs some testing and a UI to configure.

Can you test this and let me know if you find any issues?

**Comment by ddrinka** [comment]
I'll test it this evening.  Nice job pushing this out so fast!  :)

Let me think through other things that might improve functionality for us, and I'll open more issues if I come up with any.

**Comment by ddrinka** [comment]
Yeah, this works exactly how I had in my head.  Great!!
