### ISSUE TITLE
The game clock should be adjustable directly

### ISSUE THREAD

**Issue by ddrinka** [syniosis76/canoepoloscoreboard#3]
### Expected Behavior
In games where there is greater attention to the clock (finals, etc), a ref may call for the clock to be reset to a certain time.  I should be able to adjust the clock by exact seconds, or possibly set it to an exact time.

### Current Behavior
A game may be paused, and through adjusting the timing of games the clock may be adjusted (by 10-second intervals).  However this is non-intuitive, and won't work with the new pause functionality in #2.

### Proposed Change
This is a rare occurrence and shouldn't need "easy" support in the UI, to avoid accidental adjustments or more complexity for new users.  I propose a button (maybe only shown when the clock is paused) next to the pause button, that allows direct entry of the correct remaining time in the half.  It should start filled with the current time, and potentially include 10- and 1-second add/subtract buttons to avoid requiring keyboard entry.  The time delta between what's entered and what was scheduled should be subtracted from the total game as in #2, up to the 2-minute mark at which point future games should slide.

**Comment by syniosis76** [comment]
This has been implemented.
