### ISSUE TITLE
Have the score flip sides at the end of each period

### ISSUE THREAD

**Issue by ddrinka** [syniosis76/canoepoloscoreboard#4]
### Expected Behavior
The score follows the side of the pitch the team is on, so at half time the displayed score flips sides.

### Current Behavior
The score display remains fixed throughout the game.

### Proposed Fix
Add a configuration option that enables "score display flipping" automatically at the end of each period, or add a button to flip the score display manually, which resets every game.

**Comment by ddrinka** [comment]
This is low priority.  The name of each team is already displayed below the score, which I think is great.  When we've used manual score boards we flip the score around, so this would offer continuity to what has always been done, but folks can adapt to the more intuitive score-layout-stays-the-same as well.

**Comment by syniosis76** [comment]
In my experience it is not standard to swap the score around at half time, even watching worlds.

Closing this ticket.
