### ISSUE TITLE
Have an auto-pause mode

### ISSUE THREAD

**Issue by ddrinka** [syniosis76/canoepoloscoreboard#6]
Make a configurable auto-pause setting which pauses the timer at the beginning of each new period, after the countdown completes.  Pause should behave the same as #2.  This would let us drive game-start based on the ref, rather than the ref driving game-start from the timer.

**Comment by ddrinka** [comment]
I can work on this if you think it's a good idea.

**Comment by syniosis76** [comment]
I think this is a good idea and very useful.
Would you keep the countdown sounds?

One thing we don't have yet is a general configuration screen where this kind of option would be managed. We could just add one and have it accessible from the menu, or maybe a better idea would be to replace the menu with a larger popup with grouped sections to do the things already in the menu and extra configurations like this. That way I can make the server quicker to start and use.

What do you think?

I am happy for you to implement the Auto Pause feature. Add an App Setting for it, and I can incorporate that into the settings screen when done.

**Comment by ddrinka** [comment]
I think a configuration screen is a great idea. I think keep the menu for
“actions”, but move any properties to a dedicated popup.

I think the server should be a setting, and that it should auto-start on
load if it’s enabled (or when you enable it), and stop when you disable it.
Instead of it being an action, have it be a property.

But you could keep things like “load games” etc in the menu.

Just thinking out loud. I do a lot of .net but zero GUI design, so I don’t
really have a lot of insight into the best way to handle such things.
You’ve done great so far!

**Comment by syniosis76** [comment]
@ddrinka I have made a number of changes this evening including adding an Auto Pause mode. In the end I did not create a configuration window. I put the setting in the bottom right of the screen.

**Comment by syniosis76** [comment]
@ddrinka I have changed the Server Start/Stop button to an Active switch which is saved in settings, so it will automatically restart if it was turned on.

**Comment by syniosis76** [comment]
I have implemented this.
