### ISSUE TITLE
Adding a game before the next scheduled game doesn't work

### ISSUE THREAD

**Issue by ddrinka** [syniosis76/canoepoloscoreboard#7]
### Setup
The current time is 13:00.  Create games from 16:00 to 18:00.  After the countdown has started towards the 16:00 game, create a game for 13:30.

### Expected Behavior
The new game is placed in order above the previously-added games.  The countdown resets to the new time of the next game.

### Current Behavior
The new game is placed after the previously-added games.  The countdown proceeds to the first of the previously-added games.  Clicking "Restart Games" does not affect the game schedule or timer.  There is no obvious way to move the new game above the previously-added games, besides removing all the games and reloading them.

**Comment by ddrinka** [comment]
@syniosis76 Am I overlooking a way to re-sort the game schedule?

**Comment by syniosis76** [comment]
@ddrinka There is an option in the menu called Restart Games that was setup to handle this but it doesn't work in your situation as it is not expecting the new game to be at the end of the list.

I will fix the Restart Games option to sort the games before restarting.

I will also fix Add Game to automatically sort the games list and continue with the most current game.

**Comment by syniosis76** [comment]
@ddrinka I have made a number of changes this evening including sorting and restarting the games after you add new games.
